# Correct C++ chapter's .travis.yml file for 'correct_cpp_scoreboard'

script: 
  - |
    n=`cat README.md | egrep "richelbilderbeek/correct_cpp_scoreboard" | wc -l`
    if [ ! "$n" -eq "0" ]; then
      echo "Incorrect: must replace all 'richelbilderbeek/correct_cpp_scoreboard' by '[your_github_username]/correct_cpp_scoreboard'"
      exit 1
    fi

